# Generated by Django 5.2.4 on 2025-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', verbose_name=100),
            preserve_default=False,
        ),
    ]
